
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 0w3w
 */
public class step02 extends javax.swing.JFrame {

    private DefaultListModel suministrosListModel;
    private DefaultListModel suministrosTmpListModel;
    private DefaultListModel costosListModel;
    private DefaultListModel demandasListModel;
    
    /**
     * Creates new form step01
     */
    public step02() {
        suministrosListModel = new DefaultListModel();
        suministrosTmpListModel = new DefaultListModel();
        costosListModel = new DefaultListModel();
        demandasListModel = new DefaultListModel();
        initComponents();
    }
    
    public step02(DefaultListModel slm){
        suministrosListModel = slm;
        suministrosTmpListModel = slm;
        demandasListModel = new DefaultListModel();
        costosListModel = new DefaultListModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleText = new javax.swing.JLabel();
        StepTitle = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        scrollPaneSuministros = new javax.swing.JScrollPane();
        listDemandas = new javax.swing.JList(this.demandasListModel);
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nextStepBtn = new javax.swing.JButton();
        agregarCostoADemanda = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nombreDemandaTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        restartBtn = new javax.swing.JButton();
        addSuministroBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSuministro = new javax.swing.JList(this.suministrosTmpListModel);
        jScrollPane3 = new javax.swing.JScrollPane();
        listCostoSuministro = new javax.swing.JList(this.costosListModel);
        costroSuministroTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        eliminarDemandaBtn = new javax.swing.JButton();
        eliminarCostoDemanda = new javax.swing.JButton();
        cantidadDemandaTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleText.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        TitleText.setText("Método del Transporte");

        StepTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        StepTitle.setText("Paso 2");

        subTitle.setText("Agrega todas las demandas");

        listDemandas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneSuministros.setViewportView(listDemandas);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Demandas agregadas:");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Agregar Demandas");

        nextStepBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        nextStepBtn.setText("Calcular Sistema >");
        nextStepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextStepBtnActionPerformed(evt);
            }
        });

        agregarCostoADemanda.setText("Agregar");
        agregarCostoADemanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCostoADemandaActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre:");

        jLabel8.setText("Costos por Suministro:");

        restartBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        restartBtn.setText("Iniciar Nuevamente");
        restartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartBtnActionPerformed(evt);
            }
        });

        addSuministroBtn.setText("Agregar Demanda");
        addSuministroBtn.setEnabled(false);
        addSuministroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSuministroBtnActionPerformed(evt);
            }
        });

        listSuministro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listSuministro);

        listCostoSuministro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listCostoSuministro);

        jLabel1.setText("$");

        eliminarDemandaBtn.setText("Eliminar Demanda");
        eliminarDemandaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDemandaBtnActionPerformed(evt);
            }
        });

        eliminarCostoDemanda.setText("Eliminar Costo");
        eliminarCostoDemanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCostoDemandaActionPerformed(evt);
            }
        });

        jLabel9.setText("Cantidad Demanda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(restartBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextStepBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(StepTitle)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(subTitle))
                                            .addComponent(TitleText)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 179, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(agregarCostoADemanda)
                                                .addGap(186, 186, 186))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(cantidadDemandaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(scrollPaneSuministros, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(nombreDemandaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(addSuministroBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costroSuministroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eliminarCostoDemanda))
                        .addGap(266, 266, 266))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(526, Short.MAX_VALUE)
                    .addComponent(eliminarDemandaBtn)
                    .addGap(16, 16, 16)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StepTitle)
                    .addComponent(subTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPaneSuministros, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreDemandaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(cantidadDemandaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(costroSuministroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(agregarCostoADemanda))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSuministroBtn)
                    .addComponent(eliminarCostoDemanda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextStepBtn)
                    .addComponent(restartBtn))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(350, Short.MAX_VALUE)
                    .addComponent(eliminarDemandaBtn)
                    .addGap(121, 121, 121)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextStepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextStepBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextStepBtnActionPerformed

    private void restartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartBtnActionPerformed
        this.dispose();
        new main().setVisible(true);
    }//GEN-LAST:event_restartBtnActionPerformed

    private void addSuministroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSuministroBtnActionPerformed
                
    }//GEN-LAST:event_addSuministroBtnActionPerformed

    private void agregarCostoADemandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCostoADemandaActionPerformed

    }//GEN-LAST:event_agregarCostoADemandaActionPerformed

    private void eliminarDemandaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDemandaBtnActionPerformed
        int n = this.listDemandas.getSelectedIndex();
        if(n >= 0){
            this.demandasListModel.remove(n);
        }
    }//GEN-LAST:event_eliminarDemandaBtnActionPerformed

    private void eliminarCostoDemandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCostoDemandaActionPerformed
        // TODO Devolver el suministro al suministrosTmpListModel
        int n = this.listCostoSuministro.getSelectedIndex();
        if(n >= 0){
            this.costosListModel.remove(n);
        }
    }//GEN-LAST:event_eliminarCostoDemandaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StepTitle;
    private javax.swing.JLabel TitleText;
    private javax.swing.JButton addSuministroBtn;
    private javax.swing.JButton agregarCostoADemanda;
    private javax.swing.JTextField cantidadDemandaTxt;
    private javax.swing.JTextField costroSuministroTxt;
    private javax.swing.JButton eliminarCostoDemanda;
    private javax.swing.JButton eliminarDemandaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listCostoSuministro;
    private javax.swing.JList listDemandas;
    private javax.swing.JList listSuministro;
    private javax.swing.JButton nextStepBtn;
    private javax.swing.JTextField nombreDemandaTxt;
    private javax.swing.JButton restartBtn;
    private javax.swing.JScrollPane scrollPaneSuministros;
    private javax.swing.JLabel subTitle;
    // End of variables declaration//GEN-END:variables
}
